# Generated by Django 5.0.2 on 2024-02-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.JSONField()),
                ('attendance_record', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('classes_joined', models.JSONField()),
                ('classes_created', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('students', models.JSONField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
        ),
    ]
