# Generated by Django 5.0.2 on 2024-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='classes_created',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='classes_joined',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(to='home.customuser'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='attended_classes', to='home.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classes_created',
            field=models.ManyToManyField(related_name='created_by', to='home.classroom'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classes_joined',
            field=models.ManyToManyField(related_name='joined_users', to='home.classroom'),
        ),
    ]
