# Generated by Django 5.0.2 on 2024-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='classes_created',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='classes_joined',
        ),
        migrations.AddField(
            model_name='customuser',
            name='createdClasses',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joinedClasses',
            field=models.JSONField(default=[]),
        ),
    ]
