# Generated by Django 5.0.2 on 2024-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='attendance_record',
            field=models.JSONField(default=[]),
        ),
    ]
