# Generated by Django 5.0.2 on 2024-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_classroom_attendance_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='host',
        ),
        migrations.AddField(
            model_name='classroom',
            name='hostEmailId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
